### ISSUE TITLE
De-risk developing metadata forms in VueJS using JSON schema

### ISSUE THREAD

**Issue by isedwards** [opencdms-project/project-technical-team#276]
Including WMCP2 metadata in CDM

**Comment by pvgenuchten** [comment]
Hi Ian, thank you for these suggestions, back in 2021 when developing the initial prototype, vjsf seemed the most obvious choice for Vue. I haven't worked much on the project recently, so probably there are alternative options these days. 

I remember having issues with latest vuetify indeed back then already

Also vsjs does not have a spatial capability (leaflet/openlayers type widget to indicate dataset extent)

So if alternatives exist, very welcome to adopt it
